backend.msg=This must be a message
backend.build-version=1

backend.mailDetails.hostName=HostName
backend.mailDetails.port=9090
backend.mailDetails.from=Me!
backend.mailDetails.subject=Me too i guess

backend.activeBranches[0]=Bis
backend.activeBranches[1]=Lis
backend.activeBranches[2]=Dis
