backend.msg=This must be a message1
backend.build-version=11

backend.mailDetails.hostName=HostName1
backend.mailDetails.port=90901
backend.mailDetails.from=Me!1
backend.mailDetails.subject=Me too i guess1

backend.activeBranches[0]=Bis1
backend.activeBranches[1]=Lis1
backend.activeBranches[2]=Dis1
