frontend.msg=This must be a message
frontend.build-version=1

frontend.mailDetails.hostName=HostName
frontend.mailDetails.port=9090
frontend.mailDetails.from=Me!
frontend.mailDetails.subject=Me too i guess

frontend.activeBranches[0]=Bis
frontend.activeBranches[1]=Lis
frontend.activeBranches[2]=Dis
