frontend.msg=This must be a message1
frontend.build-version=11

frontend.mailDetails.hostName=HostName1
frontend.mailDetails.port=90901
frontend.mailDetails.from=Me!1
frontend.mailDetails.subject=Me too i guess1

frontend.activeBranches[0]=Bis1
frontend.activeBranches[1]=Lis1
frontend.activeBranches[2]=Dis1
